package com.haxxj.bluetoothscale.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.haxxj.bluetoothscale.DBUtils.Item_info;

import com.haxxj.bluetoothscale.greendao.Item_infoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig item_infoDaoConfig;

    private final Item_infoDao item_infoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        item_infoDaoConfig = daoConfigMap.get(Item_infoDao.class).clone();
        item_infoDaoConfig.initIdentityScope(type);

        item_infoDao = new Item_infoDao(item_infoDaoConfig, this);

        registerDao(Item_info.class, item_infoDao);
    }
    
    public void clear() {
        item_infoDaoConfig.clearIdentityScope();
    }

    public Item_infoDao getItem_infoDao() {
        return item_infoDao;
    }

}
