package com.haxxj.bluetoothscale.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.haxxj.bluetoothscale.DBUtils.Item_info;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ITEM_INFO".
*/
public class Item_infoDao extends AbstractDao<Item_info, Long> {

    public static final String TABLENAME = "ITEM_INFO";

    /**
     * Properties of entity Item_info.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Primid = new Property(0, Long.class, "primid", true, "_id");
        public final static Property Item_id = new Property(1, String.class, "item_id", false, "ITEM_ID");
        public final static Property Item_code = new Property(2, String.class, "item_code", false, "ITEM_CODE");
        public final static Property Item_name = new Property(3, String.class, "item_name", false, "ITEM_NAME");
        public final static Property Item_unit = new Property(4, String.class, "item_unit", false, "ITEM_UNIT");
        public final static Property Item_spection = new Property(5, String.class, "item_spection", false, "ITEM_SPECTION");
        public final static Property Item_iscount = new Property(6, String.class, "item_iscount", false, "ITEM_ISCOUNT");
        public final static Property Item_counting_base_number = new Property(7, Integer.class, "item_counting_base_number", false, "ITEM_COUNTING_BASE_NUMBER");
        public final static Property Item_expiration_date = new Property(8, String.class, "item_expiration_date", false, "ITEM_EXPIRATION_DATE");
        public final static Property Item_sn = new Property(9, Integer.class, "item_sn", false, "ITEM_SN");
        public final static Property Item_step_number = new Property(10, Integer.class, "item_step_number", false, "ITEM_STEP_NUMBER");
        public final static Property Item_batch_number = new Property(11, String.class, "item_batch_number", false, "ITEM_BATCH_NUMBER");
        public final static Property Item_GB = new Property(12, String.class, "item_GB", false, "ITEM__GB");
        public final static Property Item_product_code = new Property(13, String.class, "item_product_code", false, "ITEM_PRODUCT_CODE");
        public final static Property Item_price = new Property(14, Double.class, "item_price", false, "ITEM_PRICE");
        public final static Property Item_discount = new Property(15, Double.class, "item_discount", false, "ITEM_DISCOUNT");
        public final static Property Item_member_price = new Property(16, Double.class, "item_member_price", false, "ITEM_MEMBER_PRICE");
        public final static Property Item_set_number = new Property(17, Double.class, "item_set_number", false, "ITEM_SET_NUMBER");
        public final static Property Item_upper = new Property(18, Double.class, "item_upper", false, "ITEM_UPPER");
        public final static Property Item_downward = new Property(19, Double.class, "item_downward", false, "ITEM_DOWNWARD");
        public final static Property Item_scale_model = new Property(20, String.class, "item_scale_model", false, "ITEM_SCALE_MODEL");
        public final static Property Item_bill_id = new Property(21, String.class, "item_bill_id", false, "ITEM_BILL_ID");
        public final static Property Item_up_bill_id = new Property(22, String.class, "item_up_bill_id", false, "ITEM_UP_BILL_ID");
        public final static Property Item_down_bill_id = new Property(23, String.class, "item_down_bill_id", false, "ITEM_DOWN_BILL_ID");
        public final static Property Item_label_id = new Property(24, String.class, "item_label_id", false, "ITEM_LABEL_ID");
        public final static Property Item_up_label_id = new Property(25, String.class, "item_up_label_id", false, "ITEM_UP_LABEL_ID");
        public final static Property Item_down_label_id = new Property(26, String.class, "item_down_label_id", false, "ITEM_DOWN_LABEL_ID");
        public final static Property Item_remark = new Property(27, String.class, "item_remark", false, "ITEM_REMARK");
        public final static Property Item_explain = new Property(28, String.class, "item_explain", false, "ITEM_EXPLAIN");
        public final static Property Item_custom1 = new Property(29, String.class, "item_custom1", false, "ITEM_CUSTOM1");
        public final static Property Item_custom2 = new Property(30, String.class, "item_custom2", false, "ITEM_CUSTOM2");
        public final static Property Item_custom3 = new Property(31, String.class, "item_custom3", false, "ITEM_CUSTOM3");
        public final static Property Item_custom4 = new Property(32, String.class, "item_custom4", false, "ITEM_CUSTOM4");
        public final static Property Item_custom5 = new Property(33, String.class, "item_custom5", false, "ITEM_CUSTOM5");
        public final static Property Item_create_time = new Property(34, String.class, "item_create_time", false, "ITEM_CREATE_TIME");
        public final static Property Item_modify_time = new Property(35, String.class, "item_modify_time", false, "ITEM_MODIFY_TIME");
        public final static Property Item_del_time = new Property(36, String.class, "item_del_time", false, "ITEM_DEL_TIME");
        public final static Property Item_status = new Property(37, Integer.class, "item_status", false, "ITEM_STATUS");
    }


    public Item_infoDao(DaoConfig config) {
        super(config);
    }
    
    public Item_infoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ITEM_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: primid
                "\"ITEM_ID\" TEXT NOT NULL UNIQUE ," + // 1: item_id
                "\"ITEM_CODE\" TEXT," + // 2: item_code
                "\"ITEM_NAME\" TEXT," + // 3: item_name
                "\"ITEM_UNIT\" TEXT," + // 4: item_unit
                "\"ITEM_SPECTION\" TEXT," + // 5: item_spection
                "\"ITEM_ISCOUNT\" TEXT," + // 6: item_iscount
                "\"ITEM_COUNTING_BASE_NUMBER\" INTEGER," + // 7: item_counting_base_number
                "\"ITEM_EXPIRATION_DATE\" TEXT," + // 8: item_expiration_date
                "\"ITEM_SN\" INTEGER," + // 9: item_sn
                "\"ITEM_STEP_NUMBER\" INTEGER," + // 10: item_step_number
                "\"ITEM_BATCH_NUMBER\" TEXT," + // 11: item_batch_number
                "\"ITEM__GB\" TEXT," + // 12: item_GB
                "\"ITEM_PRODUCT_CODE\" TEXT," + // 13: item_product_code
                "\"ITEM_PRICE\" REAL," + // 14: item_price
                "\"ITEM_DISCOUNT\" REAL," + // 15: item_discount
                "\"ITEM_MEMBER_PRICE\" REAL," + // 16: item_member_price
                "\"ITEM_SET_NUMBER\" REAL," + // 17: item_set_number
                "\"ITEM_UPPER\" REAL," + // 18: item_upper
                "\"ITEM_DOWNWARD\" REAL," + // 19: item_downward
                "\"ITEM_SCALE_MODEL\" TEXT," + // 20: item_scale_model
                "\"ITEM_BILL_ID\" TEXT," + // 21: item_bill_id
                "\"ITEM_UP_BILL_ID\" TEXT," + // 22: item_up_bill_id
                "\"ITEM_DOWN_BILL_ID\" TEXT," + // 23: item_down_bill_id
                "\"ITEM_LABEL_ID\" TEXT," + // 24: item_label_id
                "\"ITEM_UP_LABEL_ID\" TEXT," + // 25: item_up_label_id
                "\"ITEM_DOWN_LABEL_ID\" TEXT," + // 26: item_down_label_id
                "\"ITEM_REMARK\" TEXT," + // 27: item_remark
                "\"ITEM_EXPLAIN\" TEXT," + // 28: item_explain
                "\"ITEM_CUSTOM1\" TEXT," + // 29: item_custom1
                "\"ITEM_CUSTOM2\" TEXT," + // 30: item_custom2
                "\"ITEM_CUSTOM3\" TEXT," + // 31: item_custom3
                "\"ITEM_CUSTOM4\" TEXT," + // 32: item_custom4
                "\"ITEM_CUSTOM5\" TEXT," + // 33: item_custom5
                "\"ITEM_CREATE_TIME\" TEXT," + // 34: item_create_time
                "\"ITEM_MODIFY_TIME\" TEXT," + // 35: item_modify_time
                "\"ITEM_DEL_TIME\" TEXT," + // 36: item_del_time
                "\"ITEM_STATUS\" INTEGER);"); // 37: item_status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ITEM_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Item_info entity) {
        stmt.clearBindings();
 
        Long primid = entity.getPrimid();
        if (primid != null) {
            stmt.bindLong(1, primid);
        }
        stmt.bindString(2, entity.getItem_id());
 
        String item_code = entity.getItem_code();
        if (item_code != null) {
            stmt.bindString(3, item_code);
        }
 
        String item_name = entity.getItem_name();
        if (item_name != null) {
            stmt.bindString(4, item_name);
        }
 
        String item_unit = entity.getItem_unit();
        if (item_unit != null) {
            stmt.bindString(5, item_unit);
        }
 
        String item_spection = entity.getItem_spection();
        if (item_spection != null) {
            stmt.bindString(6, item_spection);
        }
 
        String item_iscount = entity.getItem_iscount();
        if (item_iscount != null) {
            stmt.bindString(7, item_iscount);
        }
 
        Integer item_counting_base_number = entity.getItem_counting_base_number();
        if (item_counting_base_number != null) {
            stmt.bindLong(8, item_counting_base_number);
        }
 
        String item_expiration_date = entity.getItem_expiration_date();
        if (item_expiration_date != null) {
            stmt.bindString(9, item_expiration_date);
        }
 
        Integer item_sn = entity.getItem_sn();
        if (item_sn != null) {
            stmt.bindLong(10, item_sn);
        }
 
        Integer item_step_number = entity.getItem_step_number();
        if (item_step_number != null) {
            stmt.bindLong(11, item_step_number);
        }
 
        String item_batch_number = entity.getItem_batch_number();
        if (item_batch_number != null) {
            stmt.bindString(12, item_batch_number);
        }
 
        String item_GB = entity.getItem_GB();
        if (item_GB != null) {
            stmt.bindString(13, item_GB);
        }
 
        String item_product_code = entity.getItem_product_code();
        if (item_product_code != null) {
            stmt.bindString(14, item_product_code);
        }
 
        Double item_price = entity.getItem_price();
        if (item_price != null) {
            stmt.bindDouble(15, item_price);
        }
 
        Double item_discount = entity.getItem_discount();
        if (item_discount != null) {
            stmt.bindDouble(16, item_discount);
        }
 
        Double item_member_price = entity.getItem_member_price();
        if (item_member_price != null) {
            stmt.bindDouble(17, item_member_price);
        }
 
        Double item_set_number = entity.getItem_set_number();
        if (item_set_number != null) {
            stmt.bindDouble(18, item_set_number);
        }
 
        Double item_upper = entity.getItem_upper();
        if (item_upper != null) {
            stmt.bindDouble(19, item_upper);
        }
 
        Double item_downward = entity.getItem_downward();
        if (item_downward != null) {
            stmt.bindDouble(20, item_downward);
        }
 
        String item_scale_model = entity.getItem_scale_model();
        if (item_scale_model != null) {
            stmt.bindString(21, item_scale_model);
        }
 
        String item_bill_id = entity.getItem_bill_id();
        if (item_bill_id != null) {
            stmt.bindString(22, item_bill_id);
        }
 
        String item_up_bill_id = entity.getItem_up_bill_id();
        if (item_up_bill_id != null) {
            stmt.bindString(23, item_up_bill_id);
        }
 
        String item_down_bill_id = entity.getItem_down_bill_id();
        if (item_down_bill_id != null) {
            stmt.bindString(24, item_down_bill_id);
        }
 
        String item_label_id = entity.getItem_label_id();
        if (item_label_id != null) {
            stmt.bindString(25, item_label_id);
        }
 
        String item_up_label_id = entity.getItem_up_label_id();
        if (item_up_label_id != null) {
            stmt.bindString(26, item_up_label_id);
        }
 
        String item_down_label_id = entity.getItem_down_label_id();
        if (item_down_label_id != null) {
            stmt.bindString(27, item_down_label_id);
        }
 
        String item_remark = entity.getItem_remark();
        if (item_remark != null) {
            stmt.bindString(28, item_remark);
        }
 
        String item_explain = entity.getItem_explain();
        if (item_explain != null) {
            stmt.bindString(29, item_explain);
        }
 
        String item_custom1 = entity.getItem_custom1();
        if (item_custom1 != null) {
            stmt.bindString(30, item_custom1);
        }
 
        String item_custom2 = entity.getItem_custom2();
        if (item_custom2 != null) {
            stmt.bindString(31, item_custom2);
        }
 
        String item_custom3 = entity.getItem_custom3();
        if (item_custom3 != null) {
            stmt.bindString(32, item_custom3);
        }
 
        String item_custom4 = entity.getItem_custom4();
        if (item_custom4 != null) {
            stmt.bindString(33, item_custom4);
        }
 
        String item_custom5 = entity.getItem_custom5();
        if (item_custom5 != null) {
            stmt.bindString(34, item_custom5);
        }
 
        String item_create_time = entity.getItem_create_time();
        if (item_create_time != null) {
            stmt.bindString(35, item_create_time);
        }
 
        String item_modify_time = entity.getItem_modify_time();
        if (item_modify_time != null) {
            stmt.bindString(36, item_modify_time);
        }
 
        String item_del_time = entity.getItem_del_time();
        if (item_del_time != null) {
            stmt.bindString(37, item_del_time);
        }
 
        Integer item_status = entity.getItem_status();
        if (item_status != null) {
            stmt.bindLong(38, item_status);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Item_info entity) {
        stmt.clearBindings();
 
        Long primid = entity.getPrimid();
        if (primid != null) {
            stmt.bindLong(1, primid);
        }
        stmt.bindString(2, entity.getItem_id());
 
        String item_code = entity.getItem_code();
        if (item_code != null) {
            stmt.bindString(3, item_code);
        }
 
        String item_name = entity.getItem_name();
        if (item_name != null) {
            stmt.bindString(4, item_name);
        }
 
        String item_unit = entity.getItem_unit();
        if (item_unit != null) {
            stmt.bindString(5, item_unit);
        }
 
        String item_spection = entity.getItem_spection();
        if (item_spection != null) {
            stmt.bindString(6, item_spection);
        }
 
        String item_iscount = entity.getItem_iscount();
        if (item_iscount != null) {
            stmt.bindString(7, item_iscount);
        }
 
        Integer item_counting_base_number = entity.getItem_counting_base_number();
        if (item_counting_base_number != null) {
            stmt.bindLong(8, item_counting_base_number);
        }
 
        String item_expiration_date = entity.getItem_expiration_date();
        if (item_expiration_date != null) {
            stmt.bindString(9, item_expiration_date);
        }
 
        Integer item_sn = entity.getItem_sn();
        if (item_sn != null) {
            stmt.bindLong(10, item_sn);
        }
 
        Integer item_step_number = entity.getItem_step_number();
        if (item_step_number != null) {
            stmt.bindLong(11, item_step_number);
        }
 
        String item_batch_number = entity.getItem_batch_number();
        if (item_batch_number != null) {
            stmt.bindString(12, item_batch_number);
        }
 
        String item_GB = entity.getItem_GB();
        if (item_GB != null) {
            stmt.bindString(13, item_GB);
        }
 
        String item_product_code = entity.getItem_product_code();
        if (item_product_code != null) {
            stmt.bindString(14, item_product_code);
        }
 
        Double item_price = entity.getItem_price();
        if (item_price != null) {
            stmt.bindDouble(15, item_price);
        }
 
        Double item_discount = entity.getItem_discount();
        if (item_discount != null) {
            stmt.bindDouble(16, item_discount);
        }
 
        Double item_member_price = entity.getItem_member_price();
        if (item_member_price != null) {
            stmt.bindDouble(17, item_member_price);
        }
 
        Double item_set_number = entity.getItem_set_number();
        if (item_set_number != null) {
            stmt.bindDouble(18, item_set_number);
        }
 
        Double item_upper = entity.getItem_upper();
        if (item_upper != null) {
            stmt.bindDouble(19, item_upper);
        }
 
        Double item_downward = entity.getItem_downward();
        if (item_downward != null) {
            stmt.bindDouble(20, item_downward);
        }
 
        String item_scale_model = entity.getItem_scale_model();
        if (item_scale_model != null) {
            stmt.bindString(21, item_scale_model);
        }
 
        String item_bill_id = entity.getItem_bill_id();
        if (item_bill_id != null) {
            stmt.bindString(22, item_bill_id);
        }
 
        String item_up_bill_id = entity.getItem_up_bill_id();
        if (item_up_bill_id != null) {
            stmt.bindString(23, item_up_bill_id);
        }
 
        String item_down_bill_id = entity.getItem_down_bill_id();
        if (item_down_bill_id != null) {
            stmt.bindString(24, item_down_bill_id);
        }
 
        String item_label_id = entity.getItem_label_id();
        if (item_label_id != null) {
            stmt.bindString(25, item_label_id);
        }
 
        String item_up_label_id = entity.getItem_up_label_id();
        if (item_up_label_id != null) {
            stmt.bindString(26, item_up_label_id);
        }
 
        String item_down_label_id = entity.getItem_down_label_id();
        if (item_down_label_id != null) {
            stmt.bindString(27, item_down_label_id);
        }
 
        String item_remark = entity.getItem_remark();
        if (item_remark != null) {
            stmt.bindString(28, item_remark);
        }
 
        String item_explain = entity.getItem_explain();
        if (item_explain != null) {
            stmt.bindString(29, item_explain);
        }
 
        String item_custom1 = entity.getItem_custom1();
        if (item_custom1 != null) {
            stmt.bindString(30, item_custom1);
        }
 
        String item_custom2 = entity.getItem_custom2();
        if (item_custom2 != null) {
            stmt.bindString(31, item_custom2);
        }
 
        String item_custom3 = entity.getItem_custom3();
        if (item_custom3 != null) {
            stmt.bindString(32, item_custom3);
        }
 
        String item_custom4 = entity.getItem_custom4();
        if (item_custom4 != null) {
            stmt.bindString(33, item_custom4);
        }
 
        String item_custom5 = entity.getItem_custom5();
        if (item_custom5 != null) {
            stmt.bindString(34, item_custom5);
        }
 
        String item_create_time = entity.getItem_create_time();
        if (item_create_time != null) {
            stmt.bindString(35, item_create_time);
        }
 
        String item_modify_time = entity.getItem_modify_time();
        if (item_modify_time != null) {
            stmt.bindString(36, item_modify_time);
        }
 
        String item_del_time = entity.getItem_del_time();
        if (item_del_time != null) {
            stmt.bindString(37, item_del_time);
        }
 
        Integer item_status = entity.getItem_status();
        if (item_status != null) {
            stmt.bindLong(38, item_status);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Item_info readEntity(Cursor cursor, int offset) {
        Item_info entity = new Item_info( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // primid
            cursor.getString(offset + 1), // item_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // item_code
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // item_name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // item_unit
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // item_spection
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // item_iscount
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // item_counting_base_number
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // item_expiration_date
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // item_sn
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // item_step_number
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // item_batch_number
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // item_GB
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // item_product_code
            cursor.isNull(offset + 14) ? null : cursor.getDouble(offset + 14), // item_price
            cursor.isNull(offset + 15) ? null : cursor.getDouble(offset + 15), // item_discount
            cursor.isNull(offset + 16) ? null : cursor.getDouble(offset + 16), // item_member_price
            cursor.isNull(offset + 17) ? null : cursor.getDouble(offset + 17), // item_set_number
            cursor.isNull(offset + 18) ? null : cursor.getDouble(offset + 18), // item_upper
            cursor.isNull(offset + 19) ? null : cursor.getDouble(offset + 19), // item_downward
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // item_scale_model
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // item_bill_id
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // item_up_bill_id
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // item_down_bill_id
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // item_label_id
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // item_up_label_id
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // item_down_label_id
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // item_remark
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // item_explain
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // item_custom1
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // item_custom2
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // item_custom3
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // item_custom4
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // item_custom5
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // item_create_time
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // item_modify_time
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // item_del_time
            cursor.isNull(offset + 37) ? null : cursor.getInt(offset + 37) // item_status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Item_info entity, int offset) {
        entity.setPrimid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setItem_id(cursor.getString(offset + 1));
        entity.setItem_code(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setItem_name(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setItem_unit(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setItem_spection(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setItem_iscount(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setItem_counting_base_number(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setItem_expiration_date(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setItem_sn(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setItem_step_number(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setItem_batch_number(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setItem_GB(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setItem_product_code(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setItem_price(cursor.isNull(offset + 14) ? null : cursor.getDouble(offset + 14));
        entity.setItem_discount(cursor.isNull(offset + 15) ? null : cursor.getDouble(offset + 15));
        entity.setItem_member_price(cursor.isNull(offset + 16) ? null : cursor.getDouble(offset + 16));
        entity.setItem_set_number(cursor.isNull(offset + 17) ? null : cursor.getDouble(offset + 17));
        entity.setItem_upper(cursor.isNull(offset + 18) ? null : cursor.getDouble(offset + 18));
        entity.setItem_downward(cursor.isNull(offset + 19) ? null : cursor.getDouble(offset + 19));
        entity.setItem_scale_model(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setItem_bill_id(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setItem_up_bill_id(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setItem_down_bill_id(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setItem_label_id(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setItem_up_label_id(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setItem_down_label_id(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setItem_remark(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setItem_explain(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setItem_custom1(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setItem_custom2(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setItem_custom3(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setItem_custom4(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setItem_custom5(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setItem_create_time(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setItem_modify_time(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setItem_del_time(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setItem_status(cursor.isNull(offset + 37) ? null : cursor.getInt(offset + 37));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Item_info entity, long rowId) {
        entity.setPrimid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Item_info entity) {
        if(entity != null) {
            return entity.getPrimid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Item_info entity) {
        return entity.getPrimid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
